### PR TITLE
feat(hermes,grpc-sdk): route field descriptions support

### PR DESCRIPTION
**Pull request by sdimitris**
Conduit did not support description in route parameters.
Now , both GraphQL and Swagger parsers in hermes library support it.
Also field descriptions inside route responses supported.

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

### CODE REVIEW

**Review by kon14 — CHANGES_REQUESTED** [review]
This should probably introduce an optional `description` field in `Conduit*Constructor` field utility classes' `Optional()` and `Required()` getters so that descriptions can be conveniently provided without reverting to the object field definition format.

example: `status: ConduitString.Required("Updates the user's status")`

> field descriptions inside route responses supported

I was unable to reproduce this.
Can you provide an example as to how to provide these?

**Comment by sdimitris** [comment]
> This should probably introduce an optional `description` field in `Conduit*Constructor` field utility classes' `Optional()` and `Required()` getters so that descriptions can be conveniently provided without reverting to the object field definition format.
> 
> example: `status: ConduitString.Required("Updates the user's status")`
> 
> > field descriptions inside route responses supported
> 
> I was unable to reproduce this. Can you provide an example as to how to provide these?

**Comment by kon14** [comment]
> ```
>  new ConduitRouteReturnDefinition('GetUsers', {
>         users: { type:  [User.name], description: 'some description' } ,
>         count: ConduitNumber.Required,
>       }),
> ```

Tried just that. No description showed up in Swagger-UI.

**Review by kon14 — APPROVED** [review]

**Review by kkopanidis — APPROVED** [review]
LGTM!

**Pull request merged**
